#!/bin/sh
## Description: Remove the containers, volumes and data in mnt/ (run on the server by --destroy)
# The environments' destroy step (config.yaml), run on the server by
# `devopsy @<target> --destroy` before devopsy removes the directory. Locally
# it deletes the registry's images and credentials.
#
# mnt/registry belongs to the registry's UID (10001), which the deploy user
# cannot remove: init, which runs as root, deletes it.
set -eu
devopsy down --volumes --remove-orphans
devopsy run --rm --no-deps -T --entrypoint find \
  -v "$DEVOPSY_PROJECT_DIR/mnt:/devopsy-mnt" init /devopsy-mnt -mindepth 1 -delete
